In [1]:
import pandas as pd
import os
import random

In [2]:
# 导入数据
df_query = pd.DataFrame(columns = ['日期','排名','热搜词','热度'])
for filename in sorted(os.listdir('../爬虫/分小时数据')):
    path = '../爬虫/分小时数据/' + filename
    new = pd.read_excel(path)
    df_query = pd.concat([df_query,new],ignore_index=True)

df_query['date'] = df_query['日期'].apply(lambda x:x[:13])
df_query['month'] = df_query['日期'].apply(lambda x:x[:7])
df_query.head()

                    日期 排名      热搜词       热度           date    month
0  2020-01-01 00:00:00  1    谢娜的主持  3392094  2020-01-01 00  2020-01
1  2020-01-01 00:00:00  2       跨年  2378619  2020-01-01 00  2020-01
2  2020-01-01 00:00:00  3  易烊千玺太A了  1918722  2020-01-01 00  2020-01
3  2020-01-01 00:00:00  4       假唱  1739723  2020-01-01 00  2020-01
4  2020-01-01 00:00:00  5  王一博水中唱跳  1469431  2020-01-01 00  2020-01

# 分层抽样

In [23]:
sample = pd.DataFrame(columns = ['日期','排名','热搜词','热度'])
month = '2020-06'
df = df_query[df_query['month']==month]
df['day'] = df['date'].apply(lambda x:x[:10])
df.head()

<ipython-input-23-72f872974283>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['day'] = df['date'].apply(lambda x:x[:10])

,日期,排名,热搜词,热度,date,month,day
179727,2020-06-01 00:00:00,1,虞书欣 别爱我我作得很,4340698,2020-06-01 00,2020-06,2020-06-01
179728,2020-06-01 00:00:00,2,江歌母亲起诉刘鑫5日召开庭前会议,3865242,2020-06-01 00,2020-06,2020-06-01
179729,2020-06-01 00:00:00,3,陈小春二胎儿子正面照,3782198,2020-06-01 00,2020-06,2020-06-01
179730,2020-06-01 00:00:00,4,杨天真将卸任所有艺人经纪业务,2625755,2020-06-01 00,2020-06,2020-06-01
179731,2020-06-01 00:00:00,5,乘风破浪的姐姐下班照,1199147,2020-06-01 00,2020-06,2020-06-01

In [24]:
dates = []
while len(dates) < 7:
    date = random.choice(list(df['date'].unique()))
    if float(date[-2:]) >9 and float(date[-2:]) <21:
        continue
    if date in dates:
        continue
    dates.append(date)
dates.sort()
for date in dates:
    new = df[df['date']==date][['日期','排名','热搜词','热度']]
    sample = pd.concat([sample,new],ignore_index=True)
    
sample.to_excel("分层抽样-202006.xlsx",index=False)
sample.head()

                    日期 排名             热搜词      热度
0  2020-06-08 05:00:00  1          汪涵反应速度  285466
1  2020-06-08 05:00:00  2     南京茶摊奶奶又要出摊了  243756
2  2020-06-08 05:00:00  3     杨超越吐槽司机开远光灯  206747
3  2020-06-08 05:00:00  4  男观众冲上舞台向迪丽热巴求婚  175427
4  2020-06-08 05:00:00  5    陶勇谈高度近视治愈可能性   63356

In [17]:
sample = pd.DataFrame(columns = ['日期','排名','热搜词','热度'])
month = '2021-07'
df = df_query[df_query['month']==month]
dates = random.sample(list(df['date'].unique()),7)
dates.sort()
for date in dates:
    new = df[df['date']==date][['日期','排名','热搜词','热度']]
    sample = pd.concat([sample,new],ignore_index=True)
    
sample.to_excel("分层抽样-202107.xlsx",index=False)
sample.head()

                    日期 排名              热搜词       热度
0  2021-07-10 02:00:00  1       他不叫帅哥他叫吴义帆  2436011
1  2021-07-10 02:00:00  2  95后小伙在游戏里建了一个广州  1652139
2  2021-07-10 02:00:00  3   儿子被北大录取爸爸凡尔赛发言  1500449
3  2021-07-10 02:00:00  4    陶虹 不要拿生命来威胁妈妈  1406587
4  2021-07-10 02:00:00  5   张艺兴解释粉丝名叫贝壳因为硬   630403

                    日期 排名              热搜词       热度
0  2021-09-01 13:00:00  1  女子2年没复查甲状腺结节变成癌  3412887
1  2021-09-01 13:00:00  2            郑州别下了  2135253
2  2021-09-01 13:00:00  3   字节跳动取消大小周后薪资普降  1640176
3  2021-09-01 13:00:00  4  薇娅停止与田园主义全麦面包合作  1631395
4  2021-09-01 13:00:00  5     地铁安全员拖拽乘客合理吗  1476644

In [29]:
sample = pd.DataFrame(columns = ['日期','排名','热搜词','热度'])
months = list(df_query['month'].unique())
for month in months:
    df = df_query[df_query['month']==month]
    dates = random.sample(list(df['date'].unique()),7)
    dates.sort()
    for date in dates:
        new = df[df['date']==date][['日期','排名','热搜词','热度']]
        sample = pd.concat([sample,new],ignore_index=True)

In [30]:
sample.to_excel("分层抽样.xlsx",index=False)
sample.head()

                    日期 排名           热搜词       热度
0  2020-01-07 16:00:00  1      郑爽爸爸微博评论  3233504
1  2020-01-07 16:00:00  2     伊朗外长被美国拒签  1449909
2  2020-01-07 16:00:00  3  鹿晗 我状态跟你有啥关系  1433392
3  2020-01-07 16:00:00  4        现代版庆余年  1235314
4  2020-01-07 16:00:00  5  宋祖儿方否认与阮经天恋情   907979

# 系统抽样

In [13]:
sample = pd.DataFrame(columns = ['日期','排名','热搜词','热度'])
dates = list(df_query['date'].unique())
N  = len(dates)
for i in range(1,N,97):
    date = dates[i]
    new = df_query[df_query['date']==date][['日期','排名','热搜词','热度']]
    sample = pd.concat([sample,new],ignore_index=True)

In [14]:
sample.to_excel("系统抽样.xlsx",index=False)
sample.head()

                    日期 排名       热搜词       热度
0  2020-01-01 01:00:00  1    郑爽回归微博  4239536
1  2020-01-01 01:00:00  2  2020新年快乐  3639481
2  2020-01-01 01:00:00  3     吴亦凡脖子  3321843
3  2020-01-01 01:00:00  4        假唱  2462221
4  2020-01-01 01:00:00  5     谢娜的主持  1827194